create schema if not exists core;

-- 검증 계층은 raw를 직접 조회하지 않고 master view를 사용합니다.
create or replace view core.v_supplier_master as
select "공급업체코드" as supplier_id
from raw.supplier_master;
grant select on core.v_supplier_master to authenticated;
revoke all on core.v_supplier_master from anon;

create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(),
  file_name text not null,
  import_type text not null,
  import_mode text not null check (import_mode in ('append', 'upsert', 'replace')),
  total_rows integer not null default 0,
  success_rows integer not null default 0,
  warning_rows integer not null default 0,
  error_rows integer not null default 0,
  status text not null default 'STAGED' check (status in ('STAGED', 'VALIDATED', 'IMPORTED', 'ROLLED_BACK', 'FAILED')),
  uploaded_by uuid not null references auth.users(id),
  uploaded_at timestamptz not null default now(),
  imported_at timestamptz,
  forecast_stale boolean not null default false
);

create table if not exists core.import_staging (
  staging_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null,
  original_row jsonb not null,
  mapped_row jsonb not null,
  validation_status text not null default 'PENDING' check (validation_status in ('PENDING', 'SUCCESS', 'WARNING', 'ERROR')),
  unique (batch_id, row_number)
);

create table if not exists core.column_mapping (
  mapping_id bigint generated by default as identity primary key,
  import_type text not null,
  source_column text not null,
  target_column text not null,
  confirmed_by uuid references auth.users(id),
  confirmed_at timestamptz not null default now(),
  unique (import_type, source_column)
);

create table if not exists core.validation_error (
  error_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null,
  field_name text,
  error_code text not null,
  error_message text not null,
  severity text not null check (severity in ('WARNING', 'ERROR')),
  original_value jsonb
);

create index if not exists import_staging_batch_idx on core.import_staging(batch_id, row_number);
create index if not exists validation_error_batch_idx on core.validation_error(batch_id, severity, row_number);

alter table core.upload_batch enable row level security;
alter table core.import_staging enable row level security;
alter table core.column_mapping enable row level security;
alter table core.validation_error enable row level security;
revoke all on core.upload_batch, core.import_staging, core.column_mapping, core.validation_error from anon;
grant usage on schema core to authenticated;
grant select, insert on core.upload_batch, core.import_staging, core.column_mapping, core.validation_error to authenticated;
grant update on core.upload_batch, core.import_staging to authenticated;

drop policy if exists upload_batch_owner_select on core.upload_batch;
create policy upload_batch_owner_select on core.upload_batch for select to authenticated using (uploaded_by = auth.uid() or core.is_admin());
drop policy if exists upload_batch_owner_insert on core.upload_batch;
create policy upload_batch_owner_insert on core.upload_batch for insert to authenticated with check (uploaded_by = auth.uid() and core.is_active_user());
drop policy if exists upload_batch_admin_update on core.upload_batch;
create policy upload_batch_admin_update on core.upload_batch for update to authenticated using (core.is_admin()) with check (core.is_admin());

drop policy if exists import_staging_owner_select on core.import_staging;
create policy import_staging_owner_select on core.import_staging for select to authenticated using (exists (select 1 from core.upload_batch b where b.batch_id = import_staging.batch_id and (b.uploaded_by = auth.uid() or core.is_admin())));
drop policy if exists import_staging_owner_insert on core.import_staging;
create policy import_staging_owner_insert on core.import_staging for insert to authenticated with check (exists (select 1 from core.upload_batch b where b.batch_id = import_staging.batch_id and b.uploaded_by = auth.uid()));

drop policy if exists column_mapping_select on core.column_mapping;
create policy column_mapping_select on core.column_mapping for select to authenticated using (core.is_active_user());
drop policy if exists validation_error_select on core.validation_error;
create policy validation_error_select on core.validation_error for select to authenticated using (exists (select 1 from core.upload_batch b where b.batch_id = validation_error.batch_id and (b.uploaded_by = auth.uid() or core.is_admin())));
drop policy if exists validation_error_insert on core.validation_error;
create policy validation_error_insert on core.validation_error for insert to authenticated with check (exists (select 1 from core.upload_batch b where b.batch_id = validation_error.batch_id and b.uploaded_by = auth.uid()));

create or replace function core.import_batch(p_batch_id uuid, p_import_type text, p_mode text, p_rows jsonb)
returns integer language plpgsql security definer set search_path = pg_catalog, public, core, raw as $$
declare row jsonb; inserted_count integer := 0; row_number integer := 0; target_table text;
begin
  if not core.is_active_user() then raise exception '활성 사용자만 import할 수 있습니다.' using errcode = '42501'; end if;
  if p_mode = 'replace' and not core.is_admin() then raise exception 'replace는 관리자만 실행할 수 있습니다.' using errcode = '42501'; end if;
  if p_mode not in ('append', 'upsert', 'replace') then raise exception '지원하지 않는 import mode입니다.' using errcode = '22023'; end if;
  target_table := case p_import_type when 'business_event' then 'business_event' when 'sales_order' then 'sales_order' when 'item_substitute' then 'item_substitute' when 'usage_history' then 'usage_history' when 'inventory' then 'inventory' when 'item_master' then 'item_master' when 'supplier_master' then 'supplier_master' when 'purchase_order' then 'purchase_order' when 'goods_receipt' then 'goods_receipt' else null end;
  if target_table is null then raise exception '지원하지 않는 import type입니다.' using errcode = '22023'; end if;
  for row in select value from jsonb_array_elements(p_rows) loop
    row_number := row_number + 1;
    row := jsonb_set(jsonb_set(jsonb_set(row, '{batch_id}', to_jsonb(p_batch_id)), '{source_type}', '"FILE_UPLOAD"'::jsonb), '{source_record_id}', to_jsonb(coalesce(row->>'source_record_id', row->>'usage_id', row->>'sales_order_id', row->>'event_id', p_batch_id::text || ':' || row_number)));
    execute format('insert into raw.%I select (jsonb_populate_record(null::raw.%I, $1)).*', target_table, target_table) using row;
    inserted_count := inserted_count + 1;
  end loop;
  update core.upload_batch set status = 'IMPORTED', imported_at = now(), forecast_stale = p_import_type in ('usage_history','sales_order','business_event') where batch_id = p_batch_id;
  return inserted_count;
end; $$;

create or replace function core.rollback_batch(p_batch_id uuid)
returns integer language plpgsql security definer set search_path = pg_catalog, public, core, raw as $$
declare b core.upload_batch; target_table text; deleted_count integer;
begin
  select * into b from core.upload_batch where batch_id = p_batch_id;
  if not found or not (b.uploaded_by = auth.uid() or core.is_admin()) then raise exception 'batch 접근 권한이 없습니다.' using errcode = '42501'; end if;
  if b.import_mode = 'replace' then raise exception 'replace batch는 완전 rollback을 지원하지 않습니다.' using errcode = '22023'; end if;
  target_table := case b.import_type when 'business_event' then 'business_event' when 'sales_order' then 'sales_order' when 'item_substitute' then 'item_substitute' when 'usage_history' then 'usage_history' when 'inventory' then 'inventory' when 'item_master' then 'item_master' when 'supplier_master' then 'supplier_master' when 'purchase_order' then 'purchase_order' when 'goods_receipt' then 'goods_receipt' else null end;
  execute format('delete from raw.%I where batch_id = $1', target_table) using p_batch_id;
  get diagnostics deleted_count = row_count;
  update core.upload_batch set status = 'ROLLED_BACK' where batch_id = p_batch_id;
  return deleted_count;
end; $$;

revoke execute on function core.import_batch(uuid, text, text, jsonb) from public;
revoke execute on function core.rollback_batch(uuid) from public;
grant execute on function core.import_batch(uuid, text, text, jsonb) to authenticated;
grant execute on function core.rollback_batch(uuid) to authenticated;
