create schema if not exists core;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text,
  department text,
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid not null references auth.users(id),
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

create index if not exists app_user_role_active_idx on core.app_user(role, active);
create index if not exists audit_log_target_idx on core.audit_log(target_type, target_id, at desc);

create or replace function core.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public, core
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_user_set_updated_at on core.app_user;
create trigger app_user_set_updated_at
before update on core.app_user
for each row execute function core.set_updated_at();

create or replace function core.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, core
as $$
begin
  insert into core.app_user (user_id, email, name, department)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'name', ''),
    nullif(new.raw_user_meta_data ->> 'department', '')
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function core.handle_new_auth_user();

create or replace function core.is_admin()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public, core
as $$
  select exists (
    select 1
      from core.app_user
     where user_id = auth.uid()
       and role = 'ADMIN'
       and active = true
  );
$$;

create or replace function core.prevent_self_lockout()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public, core
as $$
begin
  if auth.uid() = old.user_id
     and (new.role <> old.role or new.active <> old.active)
     and (new.role <> 'ADMIN' or new.active = false) then
    raise exception '자기 자신의 관리자 권한 또는 활성 상태는 변경할 수 없습니다.' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists app_user_prevent_self_lockout on core.app_user;
create trigger app_user_prevent_self_lockout
before update on core.app_user
for each row execute function core.prevent_self_lockout();

create or replace function core.admin_change_user_role(target_user_id uuid, next_role text)
returns core.app_user
language plpgsql
security invoker
set search_path = pg_catalog, public, core
as $$
declare
  actor_id uuid := auth.uid();
  before_row core.app_user;
  after_row core.app_user;
begin
  if not core.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;
  if next_role not in ('ADMIN', 'USER') then
    raise exception '허용되지 않은 role입니다.' using errcode = '22023';
  end if;
  if actor_id = target_user_id then
    raise exception '자기 자신의 관리자 권한은 변경할 수 없습니다.' using errcode = '42501';
  end if;

  select * into before_row from core.app_user where user_id = target_user_id for update;
  if not found then
    raise exception '사용자를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  update core.app_user
     set role = next_role
   where user_id = target_user_id
   returning * into after_row;

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (actor_id, 'USER_ROLE_CHANGED', 'app_user', target_user_id::text, to_jsonb(before_row), to_jsonb(after_row));
  return after_row;
end;
$$;

create or replace function core.admin_change_user_active(target_user_id uuid, next_active boolean)
returns core.app_user
language plpgsql
security invoker
set search_path = pg_catalog, public, core
as $$
declare
  actor_id uuid := auth.uid();
  before_row core.app_user;
  after_row core.app_user;
begin
  if not core.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;
  if actor_id = target_user_id then
    raise exception '자기 자신의 활성 상태는 변경할 수 없습니다.' using errcode = '42501';
  end if;

  select * into before_row from core.app_user where user_id = target_user_id for update;
  if not found then
    raise exception '사용자를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  update core.app_user
     set active = next_active
   where user_id = target_user_id
   returning * into after_row;

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (actor_id, 'USER_ACTIVE_CHANGED', 'app_user', target_user_id::text, to_jsonb(before_row), to_jsonb(after_row));
  return after_row;
end;
$$;

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;

revoke all on table core.app_user from anon;
revoke all on table core.audit_log from anon;
grant select on table core.app_user, core.audit_log to authenticated;
grant update (role, active) on table core.app_user to authenticated;
grant usage, select on sequence core.audit_log_id_seq to authenticated;
revoke execute on function core.admin_change_user_role(uuid, text) from public;
revoke execute on function core.admin_change_user_active(uuid, boolean) from public;
grant execute on function core.admin_change_user_role(uuid, text) to authenticated;
grant execute on function core.admin_change_user_active(uuid, boolean) to authenticated;

drop policy if exists app_user_select on core.app_user;
create policy app_user_select on core.app_user
for select to authenticated
using (user_id = auth.uid() or core.is_admin());

drop policy if exists app_user_update on core.app_user;
create policy app_user_update on core.app_user
for update to authenticated
using (core.is_admin())
with check (core.is_admin());

drop policy if exists audit_log_select on core.audit_log;
create policy audit_log_select on core.audit_log
for select to authenticated
using (actor = auth.uid() or core.is_admin());

drop policy if exists audit_log_insert on core.audit_log;
create policy audit_log_insert on core.audit_log
for insert to authenticated
with check (core.is_admin() and actor = auth.uid());
